%YAML 1.1
---
sudo: false
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3
install:
  - pip install -r test-requirements.txt
  - pip install -r requirements.txt
script: nosetests
after_success:
  - codecov
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  on:
    python: 3.7
    tags: true
    all_branches: true
  user: sprockets
  password:
    secure: "Jm277mqOIrCX/UINAu4E+aZGew5MiVnX2ADISIgMHOXtYwoXNDi+WJLD4mT77/aSgkpDJc2lgIDLHy4n06rTYqPoE3mnOa/83PkcEFfynxEZN/7ZaMt6TFjdY7xEt4o8iPF3rBJMg8vdJ1mhv01rNyQkHtSBbpQ1llvGQ4/XCYpMZSLNIls8V46ynL4sxf1dZ980zp+V5XVTr79tPZswWXvZbbT/E7osJSC70KanaaNRaoOzuHRS4NJgfsuUkU4+fYII+N7nOMsTd0bdJztoNnDp+UcUiWx4lz5QX0eNWTxh05jqQ7ClD5rXo1nePd1bQ2jY6wSLUR9NxKbDLpAofaAsW8gEoS1kDVN/CAEUlzrMZjOA31t4Is3pVdZEGn4KU5U412WEtZ5NhQVqp4u/9d1/D/uDkVbLKevtHTB1WIxIjn8wk7fOlTxJa5o5CSOdL7Iijrumb8dMgx//tl+0YGMEEtCRGXCaosqN47CqbwNkomYxLpV2CBpDguUnRf60nzOl0QNI+0rIUr6fK1+ejfZUutDVUqem3VhUf41ok3ufP6WqZ3kurZ45RAHzsc3IOKjlCqYSP0wyxqDD3PLrLO1yqPnS4iHvWOErUzm/Fj0cB9U22P5sVUZBTVgOCm293cxXKo3kZb87SbF2cVNEcRu8UdUG0tj4AjUKerD+qgI="
